### PR TITLE
lfs images

### PR DESCRIPTION
**Pull request by komidore64**
This is using [`git-lfs`](https://git-lfs.github.com/). LFS stands for large file storage. It's a git plugin that replaces large files with a pointer in the git repo, and then populates the file contents in the working directory outside of git's normal file tracking.

Github offers `git-lfs` integration so there's little setup that is required.

To install `git-lfs` on Fedora 28, run:
```
dnf install git-lfs
```

After installation:
```
cd dustup
git lfs install
```

This installs the necessary git hooks into the current repository for `git-lfs` to do its thing.

Check out this pull request branch.

```
git fetch https://github.com/komidore64/dustup lfs-images
git checkout -b komidore64_lfs-images FETCH_HEAD
```

`git-lfs` knows which files to track by wildcard. You can see what its wildcards are by running `git lfs track`. If you're wanting `git-lfs` to track a file that already fits into a wildcard, just `git add` it as if nothing was different.

### CODE REVIEW

**Comment by komidore64** [comment]
refs #41

**Comment by komidore64** [comment]
okay cool. I will continue adding more character images in the same style then

**Comment by yithian** [comment]
Do you think it's worth setting this PR up as a framework and then opening separate PRs for characters' imagesets?

That way I could help pull images in, if you want.

**Comment by komidore64** [comment]
i guess i can throw his color variations in there

**Comment by komidore64** [comment]
actually, nah.

no palette colors for now.

**Comment by yithian** [comment]
let me know if and how i can help with this!

**Comment by komidore64** [comment]
I'll finish up Byakuya, then we can consider this PR "done," to allow for others to contribute images in the same fashion.

I'm currently unable to get his `minced` image to render. Probably some weirdness to do with it being a nested move. I've not dug into it yet.

**Comment by komidore64** [comment]
@yithian okay! byakuya is finally done! review away!

**Pull request merged**
