### PR TITLE
datasheet suggestions

### PR DESCRIPTION
**Pull request by komidore64**
trying to make the input strings as dumb as possible. if there are multiple possible inputs to trigger a move, it's in a separate string for clarity.

any move qualities (`(AIR OK)`) are a quality of the move rather than of its inputs, so that should probably be its own field.

DISCUSS!

### CODE REVIEW

**Comment by yithian** [comment]
> trying to make the input strings as dumb as possible. if there are multiple possible inputs to trigger a move, it's in a separate string for clarity.

This is a very good idea!

> any move qualities ((AIR OK)) are a quality of the move rather than of its inputs, so that should probably be its own field.

This makes sense too. Would it make sense to have it as part of the `conditions` field? Or do we want to use a separate `air_ok` field?

**Comment by komidore64** [comment]
> This makes sense too. Would it make sense to have it as part of the conditions field? Or do we want to use a separate air_ok field?

Hmm now we're getting into semantics. `conditions` gives me a feeling of limitations on a move, whereas a quality is more a description of a move. For instance in Under Night there are moves that are `EX OK`, I would also consider those a quality rather than a condition limiting the moves ability to fire.

Maybe our use of `conditions` here could be made more specific with `follow_up_to:` or similar?

**Comment by komidore64** [comment]
I guess I lean towards having lots of different specific keys to delineate different fields on a move, rather than one all encompassing field to catch everything, since there's really no cost to additional optional fields in yaml.

**Comment by komidore64** [comment]
after much arguing and gnashing of teeth, we (@komidore64, @yithian, @smunilla) have come to the realization that we can alleviate the need for `air_ok` and `ex_ok` fields by simply leveraging our `inputs` array.

For instance:
```
inputs:
- 236K
- j.236K
```

Or for the (later) case of Under Night `EX OK` moves:
```
inputs:
- 236A
- 236B
- 236C
```

**Pull request merged**
