### PR TITLE
Game index

### PR DESCRIPTION
**Pull request by yithian**

### CODE REVIEW

**Comment by komidore64** [comment]
would it make sense to also have yaml files for the games? so that we can map a properly capitalized title to a directory and the like?

**Comment by yithian** [comment]
Yeah, that might be a good idea. I was thinking that we could start with just `.capitalize` and `.replace('_', ' ')`. But having a proper name in the data would be nice.

**Comment by yithian** [comment]
Yeah, that might be a good idea. I was thinking that we could start with just `.capitalize` and `.replace('_', ' ')`. But having a proper name in the data would be nice.

**Comment by komidore64** [comment]
I'm okay with `.capitalize.replace('_', ' ')` for now.

**Comment by yithian** [comment]
Oh, I should add the name of the game into the game's index page! 🤦‍♂️

**Comment by komidore64** [comment]
looks good.

ACK pending rebase.

**Pull request merged**
