### PR TITLE
add ramlethal valentine from guilty gear xrd rev 2

### LINKED ISSUE #38: ramlethal is missing from gg xrd rev 2 data

### PR DESCRIPTION
**Pull request by yithian**
closes #38

### CODE REVIEW

**Comment by yithian** [comment]
@smunilla this will definitely require your +1

**Comment by komidore64** [comment]
it looks like both `2S` and `2H` already have `with sword` conditions set on them?

**Comment by smunilla** [comment]
@komidore64 Yes, but they need *specific* sword requirements. You can do 2S with your H sword out.

**Comment by komidore64** [comment]
Oh and the animation/move is different? I gotcha.

**Comment by smunilla** [comment]
Also Marteli doesn't require your S sword, Forpeli doesn't require your H sword and both return the respective sword to you.

**Comment by komidore64** [comment]
it's sounding like we should be making some edits on dustloop?

**Pull request merged**
