### PR TITLE
add yuzuriha from unist

### PR DESCRIPTION
**Pull request by yithian**
for #48

### CODE REVIEW

**Comment by komidore64** [comment]
yuzu why you gotta be so weird?

**Comment by yithian** [comment]
yuzu v weird

**Comment by komidore64** [comment]
Having sentences in the `inputs` array completely breaks any effort to have a regex validate notation. Hrmmmm

**Comment by yithian** [comment]
Maybe those instructions should be a condition instead? After all, she just ends up in the stance without having to do any extra inputs (-ish).

**Comment by komidore64** [comment]
Yeah, I think her mechanics could be shown with conditions.

**Comment by komidore64** [comment]
weird merge conflict going on.

i think maybe a rebase instead of a merge would do it?

**Comment by yithian** [comment]
Hm, I thought that's what I had done. Maybe that was just for #75 though?

Let me check what the deal is here...

**Pull request merged**
