### PR TITLE
remove universals since they're the same for everyone

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by komidore64** [comment]
#5 was merged after this one, so now this is out of date.

**Comment by yithian** [comment]
that's right! i had a question about this:

even though everyone has roughly the same inputs for universal moves, they'll all look distinct. do we want to keep these around to display the images?

**Comment by komidore64** [comment]
oh okay, that does make good sense.

i'm okay to close this PR then of others agree.

**Comment by yithian** [comment]
@smunilla do you have an opinion on this?

**Comment by smunilla** [comment]
Agreed. They might come back once we add frame data though.

**Pull request merged**
